/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package locadora.locadora.view.swing;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.locadora.negocio.dao.ReservasDAO;
import locadora.locadora.negocio.dao.UnidadesDAO;
import locadora.locadora.negocio.dao.UsuarioDAO;
import locadora.locadora.negocio.dto.Reservas;
import locadora.locadora.negocio.dto.Unidades;
import locadora.locadora.negocio.excessoes.negocioException;
import locadora.locadora.negocio.excessoes.persistenciaException;

/**
 *
 * @author gugup
 */
public class ConsultarUnidades extends javax.swing.JDialog {

    public String modo;
    String usuario;

    /**
     * Creates new form ConsultarReservas
     */
    public ConsultarUnidades(java.awt.Frame parent, boolean modal, String usuario) throws SQLException {
        super(parent, modal);
        this.usuario = usuario;
        initComponents();
        this.setLocation(((Toolkit.getDefaultToolkit().getScreenSize().width / 2) - (this.getWidth() / 2)),
                ((Toolkit.getDefaultToolkit().getScreenSize().height / 2) - (this.getHeight() / 2)));   
        modo = "Navegar";
        LoadTableContent();
    }

    public void LoadTableContent() throws SQLException {
        Object Colunas[] = {"Estado","Endereco", "Número Matrícula", "Capacidade Estoque", "Gerente responsável"};
        DefaultTableModel modelo = new DefaultTableModel(Colunas, 0);

        for (int i = 0; i < UnidadesDAO.listarUnidadesBD().size(); i++) {
            modelo.addRow(new Object[]{UnidadesDAO.listarUnidadesBD().get(i).getEstado(),UnidadesDAO.listarUnidadesBD().get(i).getLogradouro() +", "+UnidadesDAO.listarUnidadesBD().get(i).getNumero() +", "+UnidadesDAO.listarUnidadesBD().get(i).getCidade()+" - "+UnidadesDAO.listarUnidadesBD().get(i).getCep(),UnidadesDAO.listarUnidadesBD().get(i).getNumReferencia(),UnidadesDAO.listarUnidadesBD().get(i).getEstoque(),UnidadesDAO.listarUnidadesBD().get(i).getGerente()});
        }

        tlb_unidades.setModel(modelo);

    }

    public void onOff() throws SQLException {
        switch (modo) {

            case "Navegar" -> {
                btn_nova_unidade.setEnabled(true);
                btn_editar_unidade.setEnabled(false);
                btn_excluir_unidade.setEnabled(false);
                setVariavelB(modo);
            }
            case "Novo" -> {

                btn_nova_unidade.setEnabled(false);
                btn_editar_unidade.setEnabled(false);
                btn_excluir_unidade.setEnabled(false);
                setVariavelB(modo);

                LoadTableContent();
            }

            case "Editar" -> {

                btn_nova_unidade.setEnabled(true);
                btn_editar_unidade.setEnabled(false);
                btn_excluir_unidade.setEnabled(false);
                setVariavelB(modo);

                LoadTableContent();
            }

            case "Excluir" -> {

                btn_nova_unidade.setEnabled(true);
                btn_editar_unidade.setEnabled(false);
                btn_excluir_unidade.setEnabled(false);
                setVariavelB(modo);

                LoadTableContent();
            }
            case "Selecao" -> {

                btn_nova_unidade.setEnabled(true);
                btn_editar_unidade.setEnabled(true);
                btn_excluir_unidade.setEnabled(true);
                setVariavelB(modo);
            }
            default ->
                System.out.println("Inválido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlb_unidades = new javax.swing.JTable();
        btn_excluir_unidade = new javax.swing.JButton();
        btn_nova_unidade = new javax.swing.JButton();
        btn_editar_unidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades"));

        tlb_unidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlb_unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlb_unidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlb_unidades);

        btn_excluir_unidade.setText("Excluir");
        btn_excluir_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_unidadeActionPerformed(evt);
            }
        });

        btn_nova_unidade.setText("Nova");
        btn_nova_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nova_unidadeActionPerformed(evt);
            }
        });

        btn_editar_unidade.setText("Editar");
        btn_editar_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_unidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_editar_unidade)
                .addGap(227, 227, 227)
                .addComponent(btn_excluir_unidade)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(btn_nova_unidade)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir_unidade)
                    .addComponent(btn_editar_unidade))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(340, Short.MAX_VALUE)
                    .addComponent(btn_nova_unidade)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_excluir_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_unidadeActionPerformed
        int x = tlb_unidades.getSelectedRow();
        Unidades U = null;
        try {
            U = UnidadesDAO.listarUnidadesBD().get(x);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        try {
                UnidadesDAO.removerUnidadeBD(U.getCep(), usuario);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(ConsultarUnidades.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            LoadTableContent();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        modo = "Navegar";

        try {
            onOff();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_excluir_unidadeActionPerformed

    private void btn_nova_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nova_unidadeActionPerformed
        modo = "Novo";
        try {
            Controle.abrirCadastroUnidades(usuario);
        } catch (SQLException | negocioException ex) {
            Logger.getLogger(ConsultarUnidades.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVariavelB(modo);
    }//GEN-LAST:event_btn_nova_unidadeActionPerformed

    private void btn_editar_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_unidadeActionPerformed
        int x = tlb_unidades.getSelectedRow();
        modo = "Editar";
        try {
            onOff();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        setVariavelA(x);
        try {
            Controle.abrirCadastroUnidades(usuario);
        } catch (SQLException | negocioException ex) {
            Logger.getLogger(ConsultarUnidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editar_unidadeActionPerformed

    private void tlb_unidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlb_unidadesMouseClicked
        int x = tlb_unidades.getSelectedRow();
        setVariavelA(x);
        modo = "Selecao";
        try {
            onOff();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tlb_unidadesMouseClicked
    public static String b;

    public void setVariavelB(String x) {
        b = x;
    }

    public static String getVariavelB() {
        return b;
    }
    public static int a;

    public void setVariavelA(int x) {
        a = x;
    }

    public static int getVariavelA() {
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar_unidade;
    private javax.swing.JButton btn_excluir_unidade;
    private javax.swing.JButton btn_nova_unidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlb_unidades;
    // End of variables declaration//GEN-END:variables
}
